modLoader = "javafml"
loaderVersion = "[9,)"
issueTrackerURL = "https://github.com/Xupie/NetherSkybox/issues"
license = "GPL-2.0"

[[mods]]
modId = "nether_skybox"
version = "${version}"
displayName = "Nether Skybox"
authors = "Xupie"
description = '''
Adds skybox to nether so you can use custom skies.
'''
logoFile = "icon.png"

[[dependencies.nether_skybox]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.167,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nether_skybox]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.0,1.21.5)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "nether_skybox.mixins.json"
